# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ubuntu:bionic

# Install base dependencies

RUN printf "Acquire::http::Pipeline-Depth 0;\nAcquire::http::No-Cache true;\nAcquire::BrokenProxy true;" > /etc/apt/apt.conf.d/99fixbadproxy

RUN apt-get clean && \
 rm -rf /var/lib/apt/lists/* && \ 
 apt-get clean && \
 apt-get update -o Acquire::CompressionTypes::Order::=gz \
 && apt-get install -y \
 curl \
 gcc \
 libssl-dev \
 libzmq3-dev \
 pkg-config \
 unzip

ENV PATH=$PATH:/protoc3/bin:/root/.cargo/bin

# Install Rust
RUN curl https://sh.rustup.rs -sSf > /usr/bin/rustup-init \
 && chmod +x /usr/bin/rustup-init \
 && rustup-init -y

RUN rustup update \
 && rustup target add wasm32-unknown-unknown

# Install protoc
RUN curl -OLsS https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip \
 && unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local \
 && rm protoc-3.7.1-linux-x86_64.zip

WORKDIR /build

# Create empty cargo project for xo tp
RUN mkdir contracts \
 && USER=root cargo new --bin contracts/message_rust \
 && touch contracts/message_rust/src/lib.rs

# Copy over Cargo.toml file
COPY Cargo.toml /build/contracts/message_rust/Cargo.toml

# Remove sawtooth-sdk dependency. Cargo still tries to build it
# despite it not being part of the conditional target.
WORKDIR /build/contracts/message_rust
RUN sed -i -e s/sawtooth-sdk.*// Cargo.toml

# Do a release build to cache dependencies
RUN cargo build --target wasm32-unknown-unknown --release

# Remove the auto-generated .rs files and the built files
RUN rm target/wasm32-unknown-unknown/release/message-tp-rust* \
    target/wasm32-unknown-unknown/release/deps/message* \
    target/wasm32-unknown-unknown/release/libsawtooth_message.* \
    target/wasm32-unknown-unknown/release/deps/libsawtooth_message*

# Copy over source files
COPY src /build/contracts/message_rust/src

# Build the contract
RUN cargo build --target wasm32-unknown-unknown --release

# Copy the packaging directory
COPY packaging/scar/* \
     /build/contracts/message_rust/packaging/scar/

# Copy the contract to the packaging directory
RUN cp target/wasm32-unknown-unknown/release/message-tp-rust.wasm \
    packaging/scar

WORKDIR /build/contracts/message_rust/packaging/scar

# Create .scar file
RUN tar -jcvf /build/contracts/message_0.1.0.scar .
