   - identity: alpha
     endpoints:
       - tcps://splinterd-gamma:8044
     display_name: alpha
     keys:
       - 02df776e65a3e6d50df51985b3de5d36e7d05d5beb9fa613186d93556cba77770e
     metadata:
       organization: alpha

   - identity: beta
     endpoints:
       - tcps://splinterd-beta:8044
     display_name: beta
     keys:
       - 028737383c7ca45c2b2f6c39a28c069d33b34d810fd5c4c9350580c2dfff20610d
     metadata:
       organization: beta

